### ISSUE TITLE
kiwi generator should provide creating scoped container.

### ISSUE THREAD

**Issue by deep-stl** [vanlooverenkoen/kiwi#19] opened 2019-10-18 10:42 UTC
```
abstract class Injector {
  @Register.singleton(ServiceA)
  @Register.factory(Service, from: ServiceB)
  @Register.factory(ServiceB, name: 'factoryB')
  @Register.factory(ServiceC, resolvers: {ServiceB: 'factoryB'})
  void configure();
}

class Service {}

class ServiceA extends Service {}

class ServiceB extends Service {
  ServiceB(ServiceA serviceA);
}

class ServiceC extends Service {
  ServiceC(ServiceA serviceA, ServiceB serviceB);
  ServiceC.other(ServiceB serviceA);
}

void setup() {
  var injector = _$Injector();
  injector.configure();
}
```

```
class _$Injector extends Injector {
  void configure() {
    final Container container = Container();
    container.registerSingleton((c) => ServiceA());
    container
        .registerFactory<Service, ServiceB>((c) => ServiceB(c<ServiceA>()));
    container.registerFactory((c) => ServiceB(c<ServiceA>()), name: 'factoryB');
    container.registerFactory(
        (c) => ServiceC(c<ServiceA>(), c<ServiceB>('factoryB')));
  }
}
```
above we can't create scoped container, all our dependency will be store in `Container` class.someone knows how to create scoped container in generator package please provide information.

**Comment by 1ka** [comment] 2020-06-12 09:01
It would be nice if `configure()` was defined as `void configure([Container scopedContainer])` and the generator did:

```
void configure(Container scopedContainer) {
    final Container container = scopedContainer ?? Container();
```

**Comment by vanlooverenkoen** [comment] 2020-06-13 08:59
Duplicate of #6

**Comment by vanlooverenkoen** [comment] 2020-06-14 09:37
#6 already implements the kiwi implementation I will reopen this ticket for tracking the kiwi_generator implementation

**Comment by vanlooverenkoen** [comment] 2020-06-15 19:14
Fixed in
kiwi_generator => 2.0.0

**Closed by vanlooverenkoen** 2020-06-15 19:14 UTC
Labels: enhancement, kiwi_generator

**Comment by SoftWyer** [comment] 2020-06-15 21:56
@vanlooverenkoen  Brilliant, thanks for tackling this. I'll rework our current project when we have some slow-time to use this and feedback if there are any issues.

**Comment by vanlooverenkoen** [comment] 2020-06-16 05:41
Perfect.
